"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var react_1 = tslib_1.__importDefault(require("react"));
var styled_components_1 = tslib_1.__importDefault(require("styled-components"));
var common_1 = require("./common");
var StyledInput = styled_components_1.default.input(templateObject_1 || (templateObject_1 = tslib_1.__makeTemplateObject(["\n  position: relative;\n  z-index: 1;\n  display: inline-block;\n  background-color: transparent;\n  width: 100%;\n\n  ", ";\n"], ["\n  position: relative;\n  z-index: 1;\n  display: inline-block;\n  background-color: transparent;\n  width: 100%;\n\n  ", ";\n"])), common_1.commonStyles);
var Input = function (props) { return <StyledInput {...props}/>; };
exports.default = Input;
var templateObject_1;
